---
environments:
  - Development
  - Staging
  - Production

xcconfig:
    PRODUCT_BUNDLE_IDENTIFIER:
        Development: dev.duytph.Movieable.development
        Staging: dev.duytph.Movieable.staging
        Production:
            Adhoc,Debug: dev.duytph.Movieable.production
            Release: dev.duytph.Movieable
    DEEPLINK_URL_SCHEME: "#{DeeplinkUrlSchemeName}"

variables:
    baseURL: 
        Development, Staging, Production: "https://api.themoviedb.org/"
    apiVersion:
        Development, Staging, Production: 3
    apiKey:
        Development, Staging, Production: "c03c5a1d4bde7b5bd689c351d71a3bdb"
