import Foundation

/// Natrium.swift
/// Autogenerated by Natrium
///
/// - see: https://github.com/e-sites/Natrium

enum Natrium {

    enum Environment: String {
        case development = "Development"
        case production = "Production"
        case staging = "Staging"
    }

    enum Configuration: String {
        case debug = "Debug"
        case release = "Release"
    }

    enum Config {
        static let configuration: Configuration = .debug
        static let environment: Environment = .development

        static let apiKey: String = "328c283cd27bd1877d9080ccb1604c91"
        static let baseURL: String = "https://api.themoviedb.org/3"
    }
}